In [1]:
# Feature Engineering

## Objectives
#- Create lag features

#- Create rolling statistics
#- Create net pressure indicator
#- Create calendar features
#- Prepare dataset for forecasting models

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [3]:
#Load Cleaned Dataset
df = pd.read_csv(
    "../data/cleaned_uac_data.csv"
)
df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0
1,2023-01-22,32.0,49.0,39.0,7122.0,227.0
2,2023-01-23,32.0,50.0,39.0,7280.0,181.0
3,2023-01-24,47.0,42.0,47.0,7433.0,175.0
4,2023-01-25,20.0,22.0,41.0,7538.0,180.0

In [4]:
df['Date'] = pd.to_datetime(df['Date'])

df.set_index('Date', inplace=True)
df.head()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
Date,,,,,
2023-01-12,33.0,53.0,34.0,6566.0,436.0
2023-01-22,32.0,49.0,39.0,7122.0,227.0
2023-01-23,32.0,50.0,39.0,7280.0,181.0
2023-01-24,47.0,42.0,47.0,7433.0,175.0
2023-01-25,20.0,22.0,41.0,7538.0,180.0

In [5]:
#Creating Lag Features
# HHS care lag 1
df['HHS_Lag1'] = (
    df['Children in HHS Care']
    .shift(1)
)

In [6]:
#HHS care lag 2
df['HHS_Lag7'] = (
    df['Children in HHS Care']
    .shift(7)
)

In [7]:
#HHS care lag 14
df['HHS_Lag14'] = (
    df['Children in HHS Care']
    .shift(14)
)

In [8]:
#Discharge Lag Features
df['Discharge_Lag1'] = (
    df['Children discharged from HHS Care']
    .shift(1)
)

df['Discharge_Lag7'] = (
    df['Children discharged from HHS Care']
    .shift(7)
)

df['Discharge_Lag14'] = (
    df['Children discharged from HHS Care']
    .shift(14)
)

In [10]:
#Rolling Meandf['RollingMean7'] = (
df['RollingMean7'] = (
    df['Children in HHS Care']
    .rolling(7)
    .mean()
)

In [11]:
df['RollingMean14'] = (
    df['Children in HHS Care']
    .rolling(14)
    .mean()
)

In [12]:
#Rolling Standard Deviation

In [13]:
df['RollingStd7'] = (
    df['Children in HHS Care']
    .rolling(7)
    .std()
)

df['RollingStd14'] = (
    df['Children in HHS Care']
    .rolling(14)
    .std()
)

In [14]:
#Net Pressure Feature
#Net Pressure=Transfers Out of CBP−Discharges from HHS
df['NetPressure'] = (
    df['Children transferred out of CBP custody']
    -
    df['Children discharged from HHS Care']
)

In [15]:
#Calendar Features
df['DayOfWeek'] = (
    df.index.dayofweek
)

In [16]:
df['Month'] = (
    df.index.month
)

In [17]:
df['Quarter'] = (
    df.index.quarter
)

In [18]:
df['Weekend'] = (
    df.index.dayofweek >= 5
).astype(int)

In [19]:
#Check New Features
df.head(20)

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,HHS_Lag1,HHS_Lag7,HHS_Lag14,Discharge_Lag1,Discharge_Lag7,Discharge_Lag14,RollingMean7,RollingMean14,RollingStd7,RollingStd14,NetPressure,DayOfWeek,Month,Quarter,Weekend
Date,,,,,,,,,,,,,,,,,,,,
2023-01-12,33.0,53.0,34.0,6566.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-402.0,3,1,1,0
2023-01-22,32.0,49.0,39.0,7122.0,227.0,6566.0,NaN,NaN,436.0,NaN,NaN,NaN,NaN,NaN,NaN,-188.0,6,1,1,1
2023-01-23,32.0,50.0,39.0,7280.0,181.0,7122.0,NaN,NaN,227.0,NaN,NaN,NaN,NaN,NaN,NaN,-142.0,0,1,1,0
2023-01-24,47.0,42.0,47.0,7433.0,175.0,7280.0,NaN,NaN,181.0,NaN,NaN,NaN,NaN,NaN,NaN,-128.0,1,1,1,0
2023-01-25,20.0,22.0,41.0,7538.0,180.0,7433.0,NaN,NaN,175.0,NaN,NaN,NaN,NaN,NaN,NaN,-139.0,2,1,1,0
2023-01-29,23.0,45.0,11.0,7472.0,303.0,7538.0,NaN,NaN,180.0,NaN,NaN,NaN,NaN,NaN,NaN,-292.0,6,1,1,1
2023-01-30,34.0,54.0,29.0,7743.0,196.0,7472.0,NaN,NaN,303.0,NaN,NaN,7307.714286,NaN,380.917626,NaN,-167.0,0,1,1,0
2023-01-31,26.0,36.0,36.0,7803.0,158.0,7743.0,6566.0,NaN,196.0,436.0,NaN,7484.428571,NaN,240.541651,NaN,-122.0,1,1,1,0
2023-02-01,25.0,32.0,27.0,7903.0,231.0,7803.0,7122.0,NaN,158.0,227.0,NaN,7596.000000,NaN,225.045181,NaN,-204.0,2,2,1,0
2023-02-02,15.0,13.0,23.0,7879.0,298.0,7903.0,7280.0,NaN,231.0,181.0,NaN,7681.571429,NaN,196.997341,NaN,-275.0,3,2,1,0
2023-02-05,16.0,18.0,15.0,7586.0,342.0,7879.0,7433.0,NaN,298.0,175.0,NaN,7703.428571,NaN,171.682708,NaN,-327.0,6,2,1,1
2023-02-06,11.0,22.0,12.0,7720.0,196.0,7586.0,7538.0,NaN,342.0,180.0,NaN,7729.428571,NaN,155.470101,NaN,-184.0,0,2,1,0
2023-02-07,16.0,20.0,20.0,7855.0,200.0,7720.0,7472.0,NaN,196.0,303.0,NaN,7784.142857,NaN,110.731550,NaN,-180.0,1,2,1,0
2023-02-08,93.0,196.0,169.0,7915.0,317.0,7855.0,7743.0,NaN,200.0,196.0,NaN,7808.714286,7558.214286,118.865070,375.588396,-148.0,2,2,1,0
2023-02-09,124.0,234.0,161.0,7908.0,353.0,7915.0,7803.0,6566.0,317.0,158.0,436.0,7823.714286,7654.071429,124.514677,254.662209,-192.0,3,2,1,0
2023-02-12,92.0,203.0,173.0,7434.0,317.0,7908.0,7903.0,7122.0,353.0,231.0,227.0,7756.714286,7676.357143,185.827621,215.096618,-144.0,6,2,1,1
2023-02-13,186.0,259.0,172.0,7483.0,244.0,7434.0,7879.0,7280.0,317.0,298.0,181.0,7700.142857,7690.857143,201.971474,191.915389,-72.0,0,2,1,0
2023-02-14,154.0,225.0,220.0,7794.0,223.0,7483.0,7586.0,7433.0,244.0,342.0,175.0,7729.857143,7716.642857,197.633861,178.379288,-3.0,1,2,1,0
2023-02-15,91.0,199.0,172.0,7869.0,290.0,7794.0,7720.0,7538.0,223.0,196.0,180.0,7751.142857,7740.285714,204.306492,174.779610,-118.0,2,2,1,0
2023-02-16,81.0,213.0,153.0,7793.0,361.0,7869.0,7855.0,7472.0,290.0,200.0,303.0,7742.285714,7763.214286,200.359439,157.031197,-208.0,3,2,1,0

In [20]:
#Check Missing Values
df.isnull().sum()

Children apprehended and placed in CBP custody*     0
Children in CBP custody                             0
Children transferred out of CBP custody             0
Children in HHS Care                                0
Children discharged from HHS Care                   0
HHS_Lag1                                            1
HHS_Lag7                                            7
HHS_Lag14                                          14
Discharge_Lag1                                      1
Discharge_Lag7                                      7
Discharge_Lag14                                    14
RollingMean7                                        6
RollingMean14                                      13
RollingStd7                                         6
RollingStd14                                       13
NetPressure                                         0
DayOfWeek                                           0
Month                                               0
Quarter                                             0
Weekend                                             0
dtype: int64

In [21]:
df = df.dropna()
print(df.shape)

(706, 20)

In [22]:
df.to_csv(
    "../data/processed_data.csv"
)

In [23]:
df.head()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,HHS_Lag1,HHS_Lag7,HHS_Lag14,Discharge_Lag1,Discharge_Lag7,Discharge_Lag14,RollingMean7,RollingMean14,RollingStd7,RollingStd14,NetPressure,DayOfWeek,Month,Quarter,Weekend
Date,,,,,,,,,,,,,,,,,,,,
2023-02-09,124.0,234.0,161.0,7908.0,353.0,7915.0,7803.0,6566.0,317.0,158.0,436.0,7823.714286,7654.071429,124.514677,254.662209,-192.0,3,2,1,0
2023-02-12,92.0,203.0,173.0,7434.0,317.0,7908.0,7903.0,7122.0,353.0,231.0,227.0,7756.714286,7676.357143,185.827621,215.096618,-144.0,6,2,1,1
2023-02-13,186.0,259.0,172.0,7483.0,244.0,7434.0,7879.0,7280.0,317.0,298.0,181.0,7700.142857,7690.857143,201.971474,191.915389,-72.0,0,2,1,0
2023-02-14,154.0,225.0,220.0,7794.0,223.0,7483.0,7586.0,7433.0,244.0,342.0,175.0,7729.857143,7716.642857,197.633861,178.379288,-3.0,1,2,1,0
2023-02-15,91.0,199.0,172.0,7869.0,290.0,7794.0,7720.0,7538.0,223.0,196.0,180.0,7751.142857,7740.285714,204.306492,174.779610,-118.0,2,2,1,0

In [24]:
print(df.shape)

print(df.columns)

(706, 20)
Index(['Children apprehended and placed in CBP custody*',
       'Children in CBP custody', 'Children transferred out of CBP custody',
       'Children in HHS Care', 'Children discharged from HHS Care', 'HHS_Lag1',
       'HHS_Lag7', 'HHS_Lag14', 'Discharge_Lag1', 'Discharge_Lag7',
       'Discharge_Lag14', 'RollingMean7', 'RollingMean14', 'RollingStd7',
       'RollingStd14', 'NetPressure', 'DayOfWeek', 'Month', 'Quarter',
       'Weekend'],
      dtype='object')